### ISSUE TITLE
"libWrapper missing" warning when it is installed

### ISSUE THREAD

**Issue by tmcclintock** [death-save/pin-cushion#42]
Running on the Forge.

Versions:
Foundry - 0.7.9
Game system - PF2 v 1.11.18.4689
Pin Cushion - 1.2.0
libWrapper - 1.3.5.0
Browser is firefox

Upon joining the game (I'm the GM) I recieve the "Pin Cushion relies on libWrapper but it's missing yadda yadda fallback implementation". I should not be seeing this since libWrapper has been installed. I tried reinstalling pin cushion but the message still appears.

I cannot tell if the message is appearing incorrectly and PC is *actually* using libWrapper, or if PC just can't find libWrapper at all.

**Comment by eclarke12** [comment]
Hey @tmcclintock I just did some testing and what I found is that if you have libWrapper installed but not enabled in your world, you will receive the warning. Otherwise it should detect libWrapper.

Also there is an option to suppress the warning, which you can safely choose, as the "shim" we are using will ensure the wrapper is setup correctly.

**Comment by tmcclintock** [comment]
Good call. My bad, I didn't have the box checked. Sorry for the noise.
